philburk/hmsl

- hmsl/fth/load_hmsl.fth
- hmsl/fth/shape_editor.fth
- hmsl/pieces/splorp.fth
- hmsl/pieces/xforms.fth
Make timing in XFORMS and SHEP dependant on rts.rate@
Describe the instruments used in SPLORP.
> Fix some ANEW names in load_hmsl.fth

- native/osx/src/start_hmsl.sh
This allows the user to include various pieces from
the pieces folder, or tools, etc.
> Change working directory to be same as hmsl.app.

- native/osx/HMSL-OSX.xcodeproj/project.pbxproj
This will require rebuilding the pforth.dic files from scratch.
> Add floating point support.

- hmsl/broken/logto.fth
> logto: add logto.fth to broken/

- .gitignore
- native/osx/.gitignore
from https://raw.githubusercontent.com/github/gitignore/master/Objective-C.gitignore
> gitignore: improve for XCode

- native/osx/HMSL-OSX.xcodeproj/project.pbxproj
> xcode: update xcode for pforth submodule

- native/juce/Builds/MacOSX/JuceHMSL.xcodeproj/xcuserdata/phil.xcuserdatad/xcschemes/xcschememanagement.plist
- native/juce/Source/Main.cpp
- native/juce/Source/Terminal.cpp
- native/juce/Source/Terminal.h
- native/juce/Source/TerminalComponent.cpp
- native/juce/Source/TerminalComponent.h
- native/juce/Source/TerminalModel.cpp
- native/juce/Source/TerminalModel.h
Do not use AnimatedAppComponent. Just repaint when needed.
Prevent stacking of repaint requests.
Use ScrollBar instead of ViewPort
> hmsl: optimize terminal

- hmsl/pieces/trat.fth
- hmsl/tools/bend_score.fth
- hmsl/tools/score_entry.fth
Using MPE style channel rotation.
Add TRAT piano experiment.
Add BPM>TPW
Set default TPW based on 120 BPM.
> Support just intonation in score entry

- native/juce/Source/host_midi.cpp
Why did this just now stop compiling?!
> Fix casting of unique_ptr to MidiOutput

- native/juce/JuceLibraryCode/AppConfig.h
- native/juce/JuceLibraryCode/BinaryData.cpp
- native/juce/JuceLibraryCode/BinaryData.h
- native/juce/JuceLibraryCode/JuceHeader.h
> Update to new ProJUCER

- native/juce/Source/TerminalComponent.cpp
- native/juce/Source/TerminalComponent.h
> hmsl: bigger font

- hmsl/fth/time.fth
Makes editing more responsive.
We don't need such high latency these days.
> time: reduce time-advance

- hmsl/pieces/demo_behave.fth
- hmsl/screens/demo_controls.fth
- native/juce/Builds/MacOSX/JuceHMSL.xcodeproj/project.pbxproj
- native/juce/Source/LocalSynth.cpp
- native/juce/Source/LocalSynth.h
- native/juce/Source/Main.cpp
- native/juce/Source/MainComponent.cpp
- native/juce/Source/hmsl_host.h
Update version.
Some capitolization fixes.
Control grid demo size change.
> Version 0.5.3

- hmsl/tools/midifile.fth
- native/juce/Builds/MacOSX/JuceHMSL.xcodeproj/project.pbxproj
- native/juce/Builds/MacOSX/JuceHMSL.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- native/juce/JuceHMSL.jucer
- native/juce/JuceLibraryCode/AppConfig.h
- native/juce/JuceLibraryCode/BinaryData.cpp
- native/juce/JuceLibraryCode/BinaryData.h
- native/juce/Source/MainComponent.h
- native/juce/Source/pf_juce_io.cpp
reposition-file takes a double word, not a single word
Fixes #128
> midifile: fix mf.seek

- native/juce/Source/host_midi.cpp
We were leaking an audio object.
> core: fix assert on exit

- native/juce/Source/Terminal.cpp
> Show bottom lines in Terminal.

- native/juce/Source/GraphicsWindow.h
- native/juce/Source/Main.cpp
- native/juce/Source/hmsl_host_graphics.cpp
> Honor requested window size.

- hmsl/fth/load_hmsl.fth
So you can:    include hp:xforms.fth
> Add assigns for hp ht hsc

- native/juce/Source/host_midi.cpp
Fix default clock rate.
Fixes #158
> Fix slow score playing.

- hmsl/amiga/pieces/demo_draw.fth
- native/juce/Builds/MacOSX/JuceHMSL.xcodeproj/project.pbxproj
> Add .8svx to demo_draw.fth
